---
controller_execution_environments:
  - name: ansible-automation-platform-25/ee-supported-rhel9
    image: registry.redhat.io/ansible-automation-platform-25/ee-supported-rhel9
    pull: missing
    organization: "{{ my_organization }}"
    credential: registry.redhat.io

  - name: hashicorp_ee
    image: quay.io/zigfreed/hashicorp_ee:latest
    pull: missing
    organization: "{{ my_organization }}"
    credential: quay.io